### ISSUE TITLE
Homepage - Improve services content

### ISSUE THREAD

**Issue by lydenyardley** [lydenyardley/yap.agency#160]
## Services

We write fresh content. We also proofread, edit and advise on content creation for:

Web pages
Blogs
Articles
Press releases
Ebooks
Newsletters
Case studies
Advertorial
Social media posts
… you name it.

**We charge at 200 GBP per day, or 35 GBP per hour.**

[ASK US TO WRITE IT]

---

We can improve this to inspire action or at least imagination...

**Comment by lydenyardley** [comment]
Here's a list of things that is more aligned to our values and skills. It feels right to expand on each a little. What do you think?

---

We write content from scratch. We can also take what you have and supercharge it with top-notch editing. Some ideas for what we can offer you:

**Website content** - the actual presentation of your business to the online world.
**Business cards** - what it says and how it looks.
**Editing service** - Let us proofread and edit that proposal before it goes out.
**Articles** on: travel, the outdoors, health, alternative lifestyles, and good food.
**Press releases** - got a piece of news you want to put out professionally?
**Case studies/product reviews** - Lyden has an attention to detail like no other!

**We charge at 200 GBP per day, or 35 GBP per hour.**

[GIVE US A CALL]

**Comment by lydenyardley** [comment]
Update live website to match based on your positive comments. Much improved already. Over to you to refine :-)

**Comment by JaninePemberton** [comment]
We create succinct copy with minimal fuss:

Webpage content - Your homepage is the bill board for your site. The About page can cultivate a warm feeling in your customers. Each page has a clear call to action.

Articles/blogs/press releases: specialities - travel, the outdoors, health, alternative lifestyles, good food

Product reviews - we have a highly detailed, friendly style

Editing Services - let us supercharge what you already have with top-notch editing

**Comment by JaninePemberton** [comment]
Social media profiles - Sound professional AND human on LinkedIn, Twitter, Google+, Facebook

House sitting profiles - Get that house sitting job and save yourself hundreds on holiday

Business cards - Make an impact with few words

Proof reading - Those typos make you look careless - don't risk it!

**Comment by lydenyardley** [comment]
Updated and live. Added full stops and icons. Please review and close if happy. Otherwise, suggest ammendments

**Comment by JaninePemberton** [comment]
That's great, Good work. Just one amendment, something that tripped me up:

The word 'on' needs to be in bold as well as the words 'articles and blogs' in the sentence -

Articles and blogs on: travel, the outdoors, health, alternative lifestyles, good food.

**Comment by lydenyardley** [comment]
Done.
