### ISSUE TITLE
Meta-descriptions

### ISSUE THREAD

**Issue by JaninePemberton** [lydenyardley/yap.agency#163]
I'm going to offer some new meta-descriptions for our current webpages. Please edit and make sure you are happy with them before you upload them. I am a bit rusty in terms of knowing how long I can make them, so will open up a few old ones to find out...

**Comment by JaninePemberton** [comment]
/*
Home
Description: We write unique web content for businesses across the planet
Keywords: words, persuasive copy, content, trust, communication, web pages, proofreading, editing, blogs, social media profiles, house sitting profiles, written
/*

/*
Title: Home  
Description: Written words are included in Yap's websites. Improve search ranking and avoid SEO penalities with unique content and organic SEO. Attention spans are short on the web, Yap offer help to engage customers.
Keywords: search ranking, SEO, words, content, language, engagement, web writing
Template: content-and seo
*/

**Comment by JaninePemberton** [comment]
/*
About Us
Description: Janine and Lyden - the editorial team at Yap
Keywords: accurate, writing, writers, web writers, adventurous, bloggers, blogging, authors, lightweight.life
*/

**Comment by JaninePemberton** [comment]
/*
About you
Description: Writing isn't your strength - but your website needs impact
Keywords: business owners, marketing professionals, focus on what you're good at, video chat
*/

**Comment by JaninePemberton** [comment]
/*
Content & SEO  
Description: You attention span on the web is shorter than a goldfish's memory. We write copy to hold attention and engage.
Keywords: SEO, words, content, language, engagement, web writing, avoid SEO penalties, simple language, writing, organic SEO, search ranking
*/

**Comment by JaninePemberton** [comment]
/*
Contact Yap Agency
Description: Email Janine and Lyden - hello@yap.agency or send us a message via our form. Request a video chat to discuss your project.
Keywords: contact, website, email, video chat, call, telephone, email address
*/

**Comment by lydenyardley** [comment]
150 characters is the safe limit for meta descriptions. If we can make more use of them, we should. This paragraph is 148 characters and a good guide.

**Comment by JaninePemberton** [comment]
Updated meta description for home:

Make an impact with words. We write, edit and proofread web content for businesses across the globe, including web pages, blogs, articles, social media and house sitting profiles.

**Comment by JaninePemberton** [comment]
Updated meta description for About us:

We're a small editorial team - Janine and Lyden. We write simply for high impact. Details matter to us, and we never miss a deadline. Bloggers at lightweight.life

**Comment by JaninePemberton** [comment]
Updated description for About you:

You believe there is more value in collaboration than doing everything yourself; you need some help with your content writing.

**Comment by JaninePemberton** [comment]
Updated description Content & SEO:

Your attention span on the web is shorter than a goldfish's memory. We write copy to hold attention and engage, following Google's guidelines.

**Comment by JaninePemberton** [comment]
Updated description for Contact:

Getting in touch is easy; email Janine and Lyden - hello@yap.agency - or fill in a quick form to tell us about your project or request a free video chat.

**Comment by lydenyardley** [comment]
I've tweaked a couple of them for character count. Give them a once over and confirm all ok or let me know which you've changed :-)

**Comment by JaninePemberton** [comment]
Updated content and SEO meta-description.

Ready to close when done.
