### ISSUE TITLE
Homepage edit

### ISSUE THREAD

**Issue by JaninePemberton** [lydenyardley/yap.agency#164]
The homepage isn't bad, but this is a little poor:

We’ll help you sound so good that you'll attract more paying customers. And less time-wasters. Just by changing the words on your website.

If you agree, please change to:

We'll help you appeal to your target audience, and cut out the time-wasters. If you aren't completely happy with our work, we’ll give you a refund.

Find out if we’re your solution - book a no-obligation video chat.

**Comment by lydenyardley** [comment]
Agreed, and live. Close when happy :-)
