### ISSUE TITLE
About page edits

### ISSUE THREAD

**Issue by JaninePemberton** [lydenyardley/yap.agency#165]
A few changes are needed to make it simpler to read...

We are Yap

Together, we form an editorial partnership. We have incredible synergy, adding benefit over a sole writer.

We begin with an outline for the project - Lyden architects the structure and Janine creates the content. Lyden questions the direction and details, Janine re-thinks and edits.

**Everything is thought out and directed towards the ultimate goal - engaging your audience.**

Writing simply and minimally is rewarding and fun. It's also tricky. But if it was easy we'd give it up for something more challenging, or suggest you could do it just as well yourself.

Our work is immensely valuable to those who trust us to take over. We are learners and explorers, and pour hours into fine tuning our craft.

We have no plans to employ others. No apprentices, no second-rate work, and no outsourcing to Bulgaria for cheap labour. This is us.

**And we never miss a deadline.**

We are adventurous and especially enjoy projects which involve our passions; travel, the outdoors, health, alternative lifestyles, and good food.

To read more about us, or to see some examples of our honest and simple writing style, check out lightweight.LIFE.

**Comment by lydenyardley** [comment]
Agreed, and updated.
