### ISSUE TITLE
About you - edits: ideas wanted

### ISSUE THREAD

**Issue by JaninePemberton** [lydenyardley/yap.agency#166]
This isn't compelling about who our clients are. It focuses on the negative. It's patronising with the well done. It has to go. If you get a chance to, please give me a few words to describe what our clients are like. I will take the ideas and take it forwards.
We need to add developers to our list as well as business owners etc...

Our clients

We work with business owners and marketing professionals who know what they want, and need a dedicated team to make it happen.

Are your words clichéd and tired? Full of waffle and unnecessary jargon? You may be too close to the idea and have lost sight of what you really need to say.

If you've decided that you need to focus on what you're good at - well done, this is a step forward.

When you're ready for the next one, let's have a video chat. Who knows what we could uncover.

Let's talk!

**Comment by lydenyardley** [comment]
- Our clients are driven, passionate and sincerely believe in what they're doing.
- They enjoy fine things.
- They know what they want, but don't know how to make it happen.
- They've learned that there's more value in collaboration than trying to do everything yourself.

**Comment by JaninePemberton** [comment]
I have made a stackedit document in the right folder!!!

It's ready for your first edit. Anything is better than what we have, so the quicker we can change it, the better. 
See what you think!

**Comment by lydenyardley** [comment]
It's better, and I've tweaked plus added headers - need your input again

**Comment by JaninePemberton** [comment]
I think this can be closed now
