### ISSUE TITLE
Write Emails for Autoresponders

### ISSUE THREAD

**Issue by JaninePemberton** [lydenyardley/yap.agency#88]
Get together the best content for email autoresponders.
Aim at 6-10 emails.

Include stories about:

- Projecting the right Image - why important
- Reputation - why it matters in business
- Being responsive to customer needs
- Tips to help fit tasks into the day? Lift, etc
- Enjoy work, have fun

**Comment by lydenyardley** [comment]
Presumably this is no longer relevant and can be closed?

**Comment by JaninePemberton** [comment]
Yes, close it
